- apt_repository: repo='ppa:webupd8team/atom'

#- apt_key: id=98AB5139 url=https://www.virtualbox.org/download/oracle_vbox.asc state=present
#- apt_key: id=2980AECF url=https://www.virtualbox.org/download/oracle_vbox_2016.asc state=present
#- apt_repository: repo="deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"

- apt: name={{ package }} state=present
  loop_control:
    loop_var: package
  with_items:
    - atom
#    - virtualbox-5.1
